### ISSUE TITLE
Migrate from gatsby-plugin-react-helmet to Gatsby Head API

### ISSUE THREAD

**Issue by RalXYZ** [ZJUSCT/mirror-front#40]
The `gatsby-plugin-react-helmet` package will be deprecated in the future. Gatsby adds [Head API](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-head/) in gatsby@4.19.0, and the official doc suggests to use it.    
Our `gatsby-plugin-react-helmet` is added in https://github.com/ZJUSCT/mirror-front/commit/e67c3874c3ff0fab65a67278347809910785f25c by @HowyoungZhou .

**Comment by iamNCJ** [comment]
Removed this plugin in a532f9f by copying the `Helmet` source from `gatsby-plugin-react-i18next`, which introduced the dependency to this plugin. Also bumped `gatsby-plugin-react-i18next` to the latest version. The `react-helmet` package is still kept because it's still used by `gatsby-theme-material-ui-top-layout`.

**Comment by iamNCJ** [comment]
Currently the SEO part is functionally working, but we still need some typing expert to add types to all these untyped code...

**Comment by iamNCJ** [comment]
BTW, the `theme-color` meta info is relevant to #30
